" Vim syntax file
" Language:     Flat Assembler (FASM)
" Maintainer:   Gabriel Frigo <gabriel.frigo4@gmail.com>
" Last Change:  2025/04/10
" Vim URL:      http://www.vim.org/lang.html
" FASM Home:    http://flatassembler.net/
" FASM Version: 1.73.32

if version < 600
    syntax clear
elseif exists("b:current_syntax")
    finish
endif

" We need nocompatible mode in order to continue lines with backslashes.
" Original setting will be restored.
let s:cpo_save = &cpo
set cpo&vim

setlocal iskeyword=a-z,A-Z,48-57,.,_
setlocal isident=a-z,A-Z,48-57,.,_

syn case ignore

syn keyword fasmRegister ah al bh bl ch cl dh dl spl bpl sil dil
syn keyword fasmRegister r8b r9b r10b r11b r12b r13b r14b r15b
syn keyword fasmRegister ax bx cx dx ip sp bp si di
syn keyword fasmRegister r8w r9w r10w r11w r12w r13w r14w r15w
syn keyword fasmRegister eax ebx ecx edx esp ebp esi edi eip
syn keyword fasmRegister r8d r9d r10d r11d r12d r13d r14d r15d
syn keyword fasmRegister es cs ss ds fs gs
syn keyword fasmRegister rax rbx rcx rdx rsi rdi rsp rbp
syn keyword fasmRegister r0 r1 r2 r3 r4 r5 r6 r7 r8 r9
syn keyword fasmRegister r10 r11 r12 r13 r14 r15
syn keyword fasmRegister cr0 cr1 cr2 cr3 cr4 cr5 cr6 cr7
syn keyword fasmRegister dr0 dr1 dr2 dr3 dr4 dr5 dr6 dr7
syn keyword fasmRegister mm0 mm1 mm2 mm3 mm4 mm5 mm6 mm7
syn keyword fasmRegister st0 st1 st2 st3 st4 st5 st6 st7
syn keyword fasmRegister tr0 tr1 tr3 tr4 tr5 tr6 tr7
" SSE registers
syn keyword fasmRegister xmm0 xmm1 xmm2 xmm3 xmm4 xmm5 xmm6 xmm7
syn keyword fasmRegister xmm8 xmm9 xmm10 xmm11 xmm12 xmm13 xmm14 xmm15
syn keyword fasmRegister xmm16 xmm17 xmm18 xmm19 xmm20 xmm21 xmm22 xmm23
syn keyword fasmRegister xmm24 xmm25 xmm26 xmm27 xmm28 xmm29 xmm30 xmm31
" AVX registers
syn keyword fasmRegister ymm0 ymm1 ymm2 ymm3 ymm4 ymm5 ymm6 ymm7
syn keyword fasmRegister ymm8 ymm9 ymm10 ymm11 ymm12 ymm13 ymm14 ymm15
syn keyword fasmRegister ymm16 ymm17 ymm18 ymm19 ymm20 ymm21 ymm22 ymm23
syn keyword fasmRegister ymm24 ymm25 ymm26 ymm27 ymm28 ymm29 ymm30 ymm31
" AVX-512 registers
syn keyword fasmRegister zmm0 zmm1 zmm2 zmm3 zmm4 zmm5 zmm6 zmm7
syn keyword fasmRegister zmm8 zmm9 zmm10 zmm11 zmm12 zmm13 zmm14 zmm15
syn keyword fasmRegister zmm16 zmm17 zmm18 zmm19 zmm20 zmm21 zmm22 zmm23
syn keyword fasmRegister zmm24 zmm25 zmm26 zmm27 zmm28 zmm29 zmm30 zmm31

syn keyword fasmAddressSizes byte dqword dword fword large pword qword qqword
syn keyword fasmAddressSizes short tword tbyte word yword xword

syn keyword fasmDataDirectives db dd df dp dq dt du dw file rb rd rf rp rq rt rw

syn keyword fasmInstr AAA AAD AAM AAS ADC ADD AND ARPL BB0_RESET BB1_RESET BOUND BSF BSR BSWAP BT BTC BTR BTS CALL
syn keyword fasmInstr CBW CDQ CDQE CLC CLD CLI CLTS CMC CMP CMPSB CMPSD CMPSQ CMPSW CMPXCHG CMPXCHG486 CMPXCHG8B CMPXCHG16B CPUID CPU_READ CPU_WRITE CQO CWD CWDE DAA DAS DEC DIV DMINT EMMS ENTER EQU F2XM1 FABS FADD FADDP FBLD FBSTP FCHS FCLEX FCMOVB FCMOVBE FCMOVE FCMOVNB FCMOVNBE FCMOVNE FCMOVNU FCMOVU FCOM FCOMI FCOMIP FCOMP FCOMPP FCOS FDECSTP FDISI FDIV FDIVP FDIVR FDIVRP FEMMS FENI FFREE FFREEP FIADD FICOM FICOMP FIDIV FIDIVR FILD FIMUL FINCSTP FINIT FIST FISTP FISTTP FISUB FISUBR FLD FLD1 FLDCW FLDENV FLDL2E FLDL2T FLDLG2 FLDLN2 FLDPI FLDZ FMUL FMULP FNCLEX FNDISI FNENI FNINIT FNOP FNSAVE FNSTCW FNSTENV FNSTSW FPATAN FPREM FPREM1 FPTAN FRNDINT FRSTOR FSAVE FSCALE FSETPM FSIN FSINCOS FSQRT FST FSTCW FSTENV FSTP FSTSW FSUB FSUBP FSUBR FSUBRP FTST FUCOM FUCOMI FUCOMIP FUCOMP FUCOMPP FXAM FXCH FXTRACT FYL2X FYL2XP1 HLT IBTS ICEBP IDIV IMUL IN INC INSB INSD INSW INT INT01 INT1 INT03 INT3 INTO INVD INVPCID INVLPG INVLPGA IRET IRETD IRETQ IRETW JCXZ JECXZ JRCXZ JMP
syn keyword fasmInstr JMPE LAHF LAR LDS LEA LEAVE LES LFENCE LFS LGDT LGS LIDT LLDT LMSW LOADALL LOADALL286 LODSB LODSD LODSQ LODSW LOOP LOOPE LOOPNE LOOPNZ LOOPZ LSL LSS LTR MFENCE MONITOR MONITORX MOV MOVD MOVQ MOVSB MOVSD MOVSQ MOVSW MOVSX MOVSXD MOVZX MUL MWAIT MWAITX NEG NOP NOT OR OUT OUTSB OUTSD OUTSW PACKSSDW PACKSSWB PACKUSWB PADDB PADDD PADDSB PADDSIW PADDSW PADDUSB PADDUSW PADDW PAND PANDN PAUSE PAVEB PAVGUSB PCMPEQB PCMPEQD PCMPEQW PCMPGTB PCMPGTD PCMPGTW PDISTIB PF2ID PFACC PFADD PFCMPEQ PFCMPGE PFCMPGT PFMAX PFMIN PFMUL PFRCP PFRCPIT1 PFRCPIT2 PFRSQIT1 PFRSQRT PFSUB PFSUBR PI2FD PMACHRIW PMADDWD PMAGW PMULHRIW PMULHRWA PMULHRWC PMULHW PMULLW PMVGEZB PMVLZB PMVNZB PMVZB POP POPA POPAD POPAW POPF POPFD POPFQ POPFW POR PREFETCH PREFETCHW PSLLD PSLLQ PSLLW PSRAD PSRAW PSRLD PSRLQ PSRLW PSUBB PSUBD PSUBSB PSUBSIW PSUBSW PSUBUSB PSUBUSW PSUBW PUNPCKHBW PUNPCKHDQ PUNPCKHWD PUNPCKLBW PUNPCKLDQ PUNPCKLWD PUSH PUSHA PUSHAD PUSHAW PUSHF PUSHFD PUSHFQ PUSHFW PXOR RCL RCR RDSHR RDMSR RDPMC RDTSC RDTSCP RET RETF RETN RETW RETFW RETNW RETD RETFD RETND RETQ RETFQ RETNQ
syn keyword fasmInstr ROL ROR RDM RSDC RSLDT RSM RSTS SAHF SAL SALC SAR SBB SCASB SCASD SCASQ SCASW SFENCE SGDT SHL SHLD SHR SHRD SIDT SLDT SKINIT SMI SMINT SMINTOLD SMSW STC STD STI STOSB STOSD STOSQ STOSW STR SUB SVDC SVLDT SVTS SWAPGS SYSCALL SYSENTER SYSEXIT SYSRET TEST UD0 UD1 UD2B UD2 UD2A UMOV VERR VERW FWAIT WBINVD WRSHR WRMSR XADD XBTS XCHG XLATB XLAT XOR CMOVA CMOVAE CMOVB CMOVBE CMOVC CMOVE CMOVG CMOVGE CMOVL CMOVLE CMOVNA CMOVNAE CMOVNB CMOVNBE CMOVNC CMOVNE CMOVNG CMOVNGE CMOVNL CMOVNLE CMOVNO CMOVNP CMOVNS CMOVNZ CMOVO CMOVP CMOVPE CMOVPO CMOVS CMOVZ JA JAE JB JBE JC JCXZ JECXZ JRCXZ JE JG JGE JL JLE JNA JNAE JNB JNBE JNC JNE JNG JNGE JNL JNLE JNO JNP JNS JNZ JO JP JPE JPO JS JZ
syn keyword fasmInstr SETA SETAE SETB SETBE SETC SETE SETG SETGE SETL SETLE SETNA SETNAE SETNB SETNBE SETNC SETNE SETNG SETNGE SETNL SETNLE SETNO SETNP SETNS SETNZ SETO SETP SETPE SETPO SETS SETZ
syn keyword fasmInstr ADDPS ADDSS ANDNPS ANDPS CMPEQPS CMPEQSS CMPLEPS CMPLESS CMPLTPS CMPLTSS CMPNEQPS CMPNEQSS CMPNLEPS CMPNLESS CMPNLTPS CMPNLTSS CMPORDPS CMPORDSS CMPUNORDPS CMPUNORDSS CMPPS CMPSS COMISS CVTPI2PS CVTPS2PI CVTSI2SS CVTSS2SI CVTTPS2PI CVTTSS2SI DIVPS DIVSS LDMXCSR MAXPS MAXSS MINPS MINSS MOVAPS MOVHPS MOVLHPS MOVLPS MOVHLPS MOVMSKPS MOVNTPS MOVSS MOVUPS MULPS MULSS ORPS RCPPS RCPSS RSQRTPS RSQRTSS SHUFPS SQRTPS SQRTSS STMXCSR SUBPS SUBSS UCOMISS UNPCKHPS UNPCKLPS XORPS
syn keyword fasmInstr FXRSTOR FXRSTOR64 FXSAVE FXSAVE64
syn keyword fasmInstr XGETBV XSETBV XSAVE XSAVE64 XSAVEC XSAVEC64 XSAVEOPT XSAVEOPT64 XSAVES XSAVES64 XRSTOR XRSTOR64 XRSTORS XRSTORS64
syn keyword fasmInstr PREFETCHNTA PREFETCHT0 PREFETCHT1 PREFETCHT2 PREFETCHIT0 PREFETCHIT1 SFENCE
syn keyword fasmInstr MASKMOVQ MOVNTQ PAVGB PAVGW PEXTRW PINSRW PMAXSW PMAXUB PMINSW PMINUB PMOVMSKB PMULHUW PSADBW PSHUFW
syn keyword fasmInstr PF2IW PFNACC PFPNACC PI2FW PSWAPD
syn keyword fasmInstr MASKMOVDQU CLFLUSH MOVNTDQ MOVNTI MOVNTPD LFENCE MFENCE
syn keyword fasmInstr MOVD MOVDQA MOVDQU MOVDQ2Q MOVQ MOVQ2DQ PACKSSWB PACKSSDW PACKUSWB PADDB PADDW PADDD PADDQ PADDSB PADDSW PADDUSB PADDUSW PAND PANDN PAVGB PAVGW PCMPEQB PCMPEQW PCMPEQD PCMPGTB PCMPGTW PCMPGTD PEXTRW PINSRW PMADDWD PMAXSW PMAXUB PMINSW PMINUB PMOVMSKB PMULHUW PMULHW PMULLW PMULUDQ POR PSADBW PSHUFD PSHUFHW PSHUFLW PSLLDQ PSLLW PSLLD PSLLQ PSRAW PSRAD PSRLDQ PSRLW PSRLD PSRLQ PSUBB PSUBW PSUBD PSUBQ PSUBSB PSUBSW PSUBUSB PSUBUSW PUNPCKHBW PUNPCKHWD PUNPCKHDQ PUNPCKHQDQ PUNPCKLBW PUNPCKLWD PUNPCKLDQ PUNPCKLQDQ PXOR
syn keyword fasmInstr ADDPD ADDSD ANDNPD ANDPD CMPEQPD CMPEQSD CMPLEPD CMPLESD CMPLTPD CMPLTSD CMPNEQPD CMPNEQSD CMPNLEPD CMPNLESD CMPNLTPD CMPNLTSD CMPORDPD CMPORDSD CMPUNORDPD CMPUNORDSD CMPPD CMPSD COMISD CVTDQ2PD CVTDQ2PS CVTPD2DQ CVTPD2PI CVTPD2PS CVTPI2PD CVTPS2DQ CVTPS2PD CVTSD2SI CVTSD2SS CVTSI2SD CVTSS2SD CVTTPD2PI CVTTPD2DQ CVTTPS2DQ CVTTSD2SI DIVPD DIVSD MAXPD MAXSD MINPD MINSD MOVAPD MOVHPD MOVLPD MOVMSKPD MOVSD MOVUPD MULPD MULSD ORPD SHUFPD SQRTPD SQRTSD SUBPD SUBSD UCOMISD UNPCKHPD UNPCKLPD XORPD
syn keyword fasmInstr ADDSUBPD ADDSUBPS HADDPD HADDPS HSUBPD HSUBPS LDDQU MOVDDUP MOVSHDUP MOVSLDUP
syn keyword fasmInstr CLGI STGI VMCALL VMCLEAR VMFUNC VMLAUNCH VMLOAD VMMCALL VMPTRLD VMPTRST VMREAD VMRESUME VMRUN VMSAVE VMWRITE VMXOFF VMXON INVEPT INVVPID PVALIDATE RMPADJUST VMGEXIT
syn keyword fasmInstr PABSB PABSW PABSD PALIGNR PHADDW PHADDD PHADDSW PHSUBW PHSUBD PHSUBSW PMADDUBSW PMULHRSW PSHUFB PSIGNB PSIGNW PSIGND
syn keyword fasmInstr EXTRQ INSERTQ MOVNTSD MOVNTSS
syn keyword fasmInstr LZCNT
syn keyword fasmInstr BLENDPD BLENDPS BLENDVPD BLENDVPS DPPD DPPS EXTRACTPS INSERTPS MOVNTDQA MPSADBW PACKUSDW PBLENDVB PBLENDW PCMPEQQ PEXTRB PEXTRD PEXTRQ PEXTRW PHMINPOSUW PINSRB PINSRD PINSRQ PMAXSB PMAXSD PMAXUD PMAXUW PMINSB PMINSD PMINUD PMINUW PMOVSXBW PMOVSXBD PMOVSXBQ PMOVSXWD PMOVSXWQ PMOVSXDQ PMOVZXBW PMOVZXBD PMOVZXBQ PMOVZXWD PMOVZXWQ PMOVZXDQ PMULDQ PMULLD PTEST ROUNDPD ROUNDPS ROUNDSD ROUNDSS
syn keyword fasmInstr CRC32 PCMPESTRI PCMPESTRM PCMPISTRI PCMPISTRM PCMPGTQ POPCNT
syn keyword fasmInstr GETSEC
syn keyword fasmInstr PFRCPV PFRSQRTV
syn keyword fasmInstr MOVBE
syn keyword fasmInstr AESENC AESENCLAST AESDEC AESDECLAST AESIMC AESKEYGENASSIST
syn keyword fasmInstr VAESENC VAESENCLAST VAESDEC VAESDECLAST VAESIMC VAESKEYGENASSIST
syn keyword fasmInstr VADDPD VADDPS VADDSD VADDSS VADDSUBPD VADDSUBPS VANDPD VANDPS VANDNPD VANDNPS VBLENDPD VBLENDPS VBLENDVPD VBLENDVPS VBROADCASTSS VBROADCASTSD VBROADCASTF128 VCMPEQ_OSPD VCMPEQPD VCMPLT_OSPD VCMPLTPD VCMPLE_OSPD VCMPLEPD VCMPUNORD_QPD VCMPUNORDPD VCMPNEQ_UQPD VCMPNEQPD VCMPNLT_USPD VCMPNLTPD VCMPNLE_USPD VCMPNLEPD VCMPORD_QPD VCMPORDPD VCMPEQ_UQPD VCMPNGE_USPD VCMPNGEPD VCMPNGT_USPD VCMPNGTPD VCMPFALSE_OQPD VCMPFALSEPD VCMPNEQ_OQPD VCMPGE_OSPD VCMPGEPD VCMPGT_OSPD VCMPGTPD VCMPTRUE_UQPD VCMPTRUEPD VCMPLT_OQPD VCMPLE_OQPD VCMPUNORD_SPD VCMPNEQ_USPD VCMPNLT_UQPD VCMPNLE_UQPD VCMPORD_SPD VCMPEQ_USPD VCMPNGE_UQPD VCMPNGT_UQPD VCMPFALSE_OSPD VCMPNEQ_OSPD VCMPGE_OQPD VCMPGT_OQPD VCMPTRUE_USPD VCMPPD VCMPEQ_OSPS VCMPEQPS VCMPLT_OSPS VCMPLTPS VCMPLE_OSPS VCMPLEPS VCMPUNORD_QPS VCMPUNORDPS VCMPNEQ_UQPS VCMPNEQPS VCMPNLT_USPS VCMPNLTPS VCMPNLE_USPS VCMPNLEPS VCMPORD_QPS VCMPORDPS VCMPEQ_UQPS VCMPNGE_USPS VCMPNGEPS VCMPNGT_USPS VCMPNGTPS VCMPFALSE_OQPS VCMPFALSEPS VCMPNEQ_OQPS VCMPGE_OSPS VCMPGEPS VCMPGT_OSPS VCMPGTPS VCMPTRUE_UQPS VCMPTRUEPS VCMPLT_OQPS VCMPLE_OQPS VCMPUNORD_SPS VCMPNEQ_USPS VCMPNLT_UQPS VCMPNLE_UQPS VCMPORD_SPS VCMPEQ_USPS VCMPNGE_UQPS VCMPNGT_UQPS VCMPFALSE_OSPS VCMPNEQ_OSPS VCMPGE_OQPS VCMPGT_OQPS VCMPTRUE_USPS VCMPPS VCMPEQ_OSSD VCMPEQSD VCMPLT_OSSD VCMPLTSD VCMPLE_OSSD VCMPLESD VCMPUNORD_QSD VCMPUNORDSD VCMPNEQ_UQSD VCMPNEQSD VCMPNLT_USSD VCMPNLTSD VCMPNLE_USSD VCMPNLESD VCMPORD_QSD VCMPORDSD VCMPEQ_UQSD VCMPNGE_USSD VCMPNGESD VCMPNGT_USSD VCMPNGTSD VCMPFALSE_OQSD VCMPFALSESD VCMPNEQ_OQSD VCMPGE_OSSD VCMPGESD VCMPGT_OSSD VCMPGTSD VCMPTRUE_UQSD VCMPTRUESD VCMPLT_OQSD VCMPLE_OQSD VCMPUNORD_SSD VCMPNEQ_USSD VCMPNLT_UQSD VCMPNLE_UQSD VCMPORD_SSD VCMPEQ_USSD VCMPNGE_UQSD VCMPNGT_UQSD VCMPFALSE_OSSD VCMPNEQ_OSSD VCMPGE_OQSD VCMPGT_OQSD VCMPTRUE_USSD VCMPSD VCMPEQ_OSSS VCMPEQSS VCMPLT_OSSS VCMPLTSS VCMPLE_OSSS VCMPLESS VCMPUNORD_QSS VCMPUNORDSS VCMPNEQ_UQSS VCMPNEQSS VCMPNLT_USSS VCMPNLTSS VCMPNLE_USSS VCMPNLESS VCMPORD_QSS VCMPORDSS VCMPEQ_UQSS VCMPNGE_USSS VCMPNGESS VCMPNGT_USSS VCMPNGTSS VCMPFALSE_OQSS VCMPFALSESS VCMPNEQ_OQSS VCMPGE_OSSS VCMPGESS VCMPGT_OSSS VCMPGTSS VCMPTRUE_UQSS VCMPTRUESS VCMPLT_OQSS VCMPLE_OQSS VCMPUNORD_SSS VCMPNEQ_USSS VCMPNLT_UQSS VCMPNLE_UQSS VCMPORD_SSS VCMPEQ_USSS VCMPNGE_UQSS VCMPNGT_UQSS VCMPFALSE_OSSS VCMPNEQ_OSSS VCMPGE_OQSS VCMPGT_OQSS VCMPTRUE_USSS VCMPSS VCOMISD VCOMISS VCVTDQ2PD VCVTDQ2PS VCVTPD2DQ VCVTPD2PS VCVTPS2DQ VCVTPS2PD VCVTSD2SI VCVTSD2SS VCVTSI2SD VCVTSI2SS VCVTSS2SD VCVTSS2SI VCVTTPD2DQ VCVTTPS2DQ VCVTTSD2SI VCVTTSS2SI VDIVPD VDIVPS VDIVSD VDIVSS VDPPD VDPPS VEXTRACTF128 VEXTRACTPS VHADDPD VHADDPS VHSUBPD VHSUBPS VINSERTF128 VINSERTPS VLDDQU VLDQQU VLDMXCSR VMASKMOVDQU VMASKMOVPS VMASKMOVPD VMAXPD VMAXPS VMAXSD VMAXSS VMINPD VMINPS VMINSD VMINSS VMOVAPD VMOVAPS VMOVD VMOVQ VMOVDDUP VMOVDQA VMOVQQA VMOVDQU VMOVQQU VMOVHLPS VMOVHPD VMOVHPS VMOVLHPS VMOVLPD VMOVLPS VMOVMSKPD VMOVMSKPS VMOVNTDQ VMOVNTQQ VMOVNTDQA VMOVNTPD VMOVNTPS VMOVSD VMOVSHDUP VMOVSLDUP VMOVSS VMOVUPD VMOVUPS VMPSADBW VMULPD VMULPS VMULSD VMULSS VORPD VORPS VPABSB VPABSW VPABSD VPACKSSWB VPACKSSDW VPACKUSWB VPACKUSDW VPADDB VPADDW VPADDD VPADDQ VPADDSB VPADDSW VPADDUSB VPADDUSW VPALIGNR VPAND VPANDN VPAVGB VPAVGW VPBLENDVB VPBLENDW VPCMPESTRI VPCMPESTRM VPCMPISTRI VPCMPISTRM VPCMPEQB VPCMPEQW VPCMPEQD VPCMPEQQ VPCMPGTB VPCMPGTW VPCMPGTD VPCMPGTQ VPERMILPD VPERMILPS VPERM2F128 VPEXTRB VPEXTRW VPEXTRD VPEXTRQ VPHADDW VPHADDD VPHADDSW VPHMINPOSUW VPHSUBW VPHSUBD VPHSUBSW VPINSRB VPINSRW VPINSRD VPINSRQ VPMADDWD VPMADDUBSW VPMAXSB VPMAXSW VPMAXSD VPMAXUB VPMAXUW VPMAXUD VPMINSB VPMINSW VPMINSD VPMINUB VPMINUW VPMINUD VPMOVMSKB VPMOVSXBW VPMOVSXBD VPMOVSXBQ VPMOVSXWD VPMOVSXWQ VPMOVSXDQ VPMOVZXBW VPMOVZXBD VPMOVZXBQ VPMOVZXWD VPMOVZXWQ VPMOVZXDQ VPMULHUW VPMULHRSW VPMULHW VPMULLW VPMULLD VPMULUDQ VPMULDQ VPOR VPSADBW VPSHUFB VPSHUFD VPSHUFHW VPSHUFLW VPSIGNB VPSIGNW VPSIGND VPSLLDQ VPSRLDQ VPSLLW VPSLLD VPSLLQ VPSRAW VPSRAD VPSRLW VPSRLD VPSRLQ VPTEST VPSUBB VPSUBW VPSUBD VPSUBQ VPSUBSB VPSUBSW VPSUBUSB VPSUBUSW VPUNPCKHBW VPUNPCKHWD VPUNPCKHDQ VPUNPCKHQDQ VPUNPCKLBW VPUNPCKLWD VPUNPCKLDQ VPUNPCKLQDQ VPXOR VRCPPS VRCPSS VRSQRTPS VRSQRTSS VROUNDPD VROUNDPS VROUNDSD VROUNDSS VSHUFPD VSHUFPS VSQRTPD VSQRTPS VSQRTSD VSQRTSS VSTMXCSR VSUBPD VSUBPS VSUBSD VSUBSS VTESTPS VTESTPD VUCOMISD VUCOMISS VUNPCKHPD VUNPCKHPS VUNPCKLPD VUNPCKLPS VXORPD VXORPS VZEROALL VZEROUPPER
syn keyword fasmInstr PCLMULLQLQDQ PCLMULHQLQDQ PCLMULLQHQDQ PCLMULHQHQDQ PCLMULQDQ
syn keyword fasmInstr VPCLMULLQLQDQ VPCLMULHQLQDQ VPCLMULLQHQDQ VPCLMULHQHQDQ VPCLMULQDQ
syn keyword fasmInstr VFMADD132PS VFMADD132PD VFMADD312PS VFMADD312PD VFMADD213PS VFMADD213PD VFMADD123PS VFMADD123PD VFMADD231PS VFMADD231PD VFMADD321PS VFMADD321PD VFMADDSUB132PS VFMADDSUB132PD VFMADDSUB312PS VFMADDSUB312PD VFMADDSUB213PS VFMADDSUB213PD VFMADDSUB123PS VFMADDSUB123PD VFMADDSUB231PS VFMADDSUB231PD VFMADDSUB321PS VFMADDSUB321PD VFMSUB132PS VFMSUB132PD VFMSUB312PS VFMSUB312PD VFMSUB213PS VFMSUB213PD VFMSUB123PS VFMSUB123PD VFMSUB231PS VFMSUB231PD VFMSUB321PS VFMSUB321PD VFMSUBADD132PS VFMSUBADD132PD VFMSUBADD312PS VFMSUBADD312PD VFMSUBADD213PS VFMSUBADD213PD VFMSUBADD123PS VFMSUBADD123PD VFMSUBADD231PS VFMSUBADD231PD VFMSUBADD321PS VFMSUBADD321PD VFNMADD132PS VFNMADD132PD VFNMADD312PS VFNMADD312PD VFNMADD213PS VFNMADD213PD VFNMADD123PS VFNMADD123PD VFNMADD231PS VFNMADD231PD VFNMADD321PS VFNMADD321PD VFNMSUB132PS VFNMSUB132PD VFNMSUB312PS VFNMSUB312PD VFNMSUB213PS VFNMSUB213PD VFNMSUB123PS VFNMSUB123PD VFNMSUB231PS VFNMSUB231PD VFNMSUB321PS VFNMSUB321PD VFMADD132SS VFMADD132SD VFMADD312SS VFMADD312SD VFMADD213SS VFMADD213SD VFMADD123SS VFMADD123SD VFMADD231SS VFMADD231SD VFMADD321SS VFMADD321SD VFMSUB132SS VFMSUB132SD VFMSUB312SS VFMSUB312SD VFMSUB213SS VFMSUB213SD VFMSUB123SS VFMSUB123SD VFMSUB231SS VFMSUB231SD VFMSUB321SS VFMSUB321SD VFNMADD132SS VFNMADD132SD VFNMADD312SS VFNMADD312SD VFNMADD213SS VFNMADD213SD VFNMADD123SS VFNMADD123SD VFNMADD231SS VFNMADD231SD VFNMADD321SS VFNMADD321SD VFNMSUB132SS VFNMSUB132SD VFNMSUB312SS VFNMSUB312SD VFNMSUB213SS VFNMSUB213SD VFNMSUB123SS VFNMSUB123SD VFNMSUB231SS VFNMSUB231SD VFNMSUB321SS VFNMSUB321SD
syn keyword fasmInstr RDFSBASE RDGSBASE RDRAND WRFSBASE WRGSBASE VCVTPH2PS VCVTPS2PH
syn keyword fasmInstr ADCX ADOX RDSEED
syn keyword fasmInstr CLAC STAC
syn keyword fasmInstr XSTORE XCRYPTECB XCRYPTCBC XCRYPTCTR XCRYPTCFB XCRYPTOFB MONTMUL XSHA1 XSHA256
syn keyword fasmInstr LLWPCB
syn keyword fasmInstr SLWPCB
syn keyword fasmInstr LWPVAL
syn keyword fasmInstr LWPINS
syn keyword fasmInstr VFMADDPD
syn keyword fasmInstr VFMADDPS
syn keyword fasmInstr VFMADDSD
syn keyword fasmInstr VFMADDSS
syn keyword fasmInstr VFMADDSUBPD
syn keyword fasmInstr VFMADDSUBPS
syn keyword fasmInstr VFMSUBADDPD
syn keyword fasmInstr VFMSUBADDPS
syn keyword fasmInstr VFMSUBPD
syn keyword fasmInstr VFMSUBPS
syn keyword fasmInstr VFMSUBSD
syn keyword fasmInstr VFMSUBSS
syn keyword fasmInstr VFNMADDPD
syn keyword fasmInstr VFNMADDPS
syn keyword fasmInstr VFNMADDSD
syn keyword fasmInstr VFNMADDSS
syn keyword fasmInstr VFNMSUBPD
syn keyword fasmInstr VFNMSUBPS
syn keyword fasmInstr VFNMSUBSD
syn keyword fasmInstr VFNMSUBSS
syn keyword fasmInstr VFRCZPD
syn keyword fasmInstr VFRCZPS
syn keyword fasmInstr VFRCZSD
syn keyword fasmInstr VFRCZSS VPCMOV
syn keyword fasmInstr VPCOMB VPCOMD VPCOMQ VPCOMUB VPCOMUD VPCOMUQ VPCOMUW VPCOMW
syn keyword fasmInstr VPHADDBD VPHADDBQ VPHADDBW VPHADDDQ VPHADDUBD VPHADDUBQ VPHADDUBW VPHADDUDQ VPHADDUWD VPHADDUWQ VPHADDWD VPHADDWQ
syn keyword fasmInstr VPHSUBBW VPHSUBDQ VPHSUBWD
syn keyword fasmInstr VPMACSDD VPMACSDQH VPMACSDQL VPMACSSDD VPMACSSDQH VPMACSSDQL VPMACSSWD VPMACSSWW VPMACSWD VPMACSWW VPMADCSSWD VPMADCSWD
syn keyword fasmInstr VPPERM
syn keyword fasmInstr VPROTB
syn keyword fasmInstr VPROTD VPROTQ VPROTW
syn keyword fasmInstr VPSHAB
syn keyword fasmInstr VPSHAD
syn keyword fasmInstr VPSHAQ
syn keyword fasmInstr VPSHAW
syn keyword fasmInstr VPSHLB
syn keyword fasmInstr VPSHLD
syn keyword fasmInstr VPSHLQ
syn keyword fasmInstr VPSHLW
syn keyword fasmInstr VBROADCASTI128 VPBLENDD VPBROADCASTB VPBROADCASTW VPBROADCASTD VPBROADCASTQ
syn keyword fasmInstr VPERMD VPERMPD VPERMPS VPERMQ VPERM2I128 VEXTRACTI128
syn keyword fasmInstr VINSERTI128 VPMASKMOVD VPMASKMOVQ
syn keyword fasmInstr VPSLLVD VPSLLVQ
syn keyword fasmInstr VPSRAVD
syn keyword fasmInstr VPSRLVD VPSRLVQ
syn keyword fasmInstr VGATHERDPD VGATHERQPD
syn keyword fasmInstr VGATHERDPS VGATHERQPS
syn keyword fasmInstr VPGATHERDD VPGATHERQD
syn keyword fasmInstr VPGATHERDQ VPGATHERQQ
syn keyword fasmInstr XABORT XBEGIN XEND XTEST
syn keyword fasmInstr ANDN BEXTR BLCI BLCIC BLSI BLSIC BLCFILL BLSFILL BLCMSK BLSMSK BLSR BLCS BZHI MULX PDEP PEXT RORX SARX SHLX SHRX TZCNT TZMSK T1MSKC
syn keyword fasmInstr PREFETCHWT1
syn keyword fasmInstr BNDMK BNDCL BNDCU BNDCN BNDMOV BNDLDX BNDSTX
syn keyword fasmInstr SHA1MSG1 SHA1MSG2 SHA1NEXTE SHA1RNDS4 SHA256MSG1 SHA256MSG2 SHA256RNDS2 VSHA512MSG1 VSHA512MSG2 VSHA512RNDS2
syn keyword fasmInstr VSM3MSG1 VSM3MSG2 VSM3RNDS2
syn keyword fasmInstr VSM4KEY4 VSM4RNDS4
syn keyword fasmInstr VBCSTNEBF16PS VBCSTNESH2PS VCVTNEEBF162PS VCVTNEEPH2PS VCVTNEOBF162PS VCVTNEOPH2PS VCVTNEPS2BF16
syn keyword fasmInstr VPDPBSSD VPDPBSSDS VPDPBSUD VPDPBSUDS VPDPBUUD VPDPBUUDS
syn keyword fasmInstr VPMADD52HUQ VPMADD52LUQ
syn keyword fasmInstr KADDB KADDD KADDQ KADDW KANDB KANDD KANDNB KANDND KANDNQ KANDNW KANDQ KANDW KMOVB KMOVD KMOVQ KMOVW KNOTB KNOTD KNOTQ KNOTW KORB KORD KORQ KORW KORTESTB KORTESTD KORTESTQ KORTESTW KSHIFTLB KSHIFTLD KSHIFTLQ KSHIFTLW KSHIFTRB KSHIFTRD KSHIFTRQ KSHIFTRW KTESTB KTESTD KTESTQ KTESTW KUNPCKBW KUNPCKDQ KUNPCKWD KXNORB KXNORD KXNORQ KXNORW KXORB KXORD KXORQ KXORW
syn keyword fasmInstr KADD KAND KANDN KMOV KNOT KOR KORTEST KSHIFTL KSHIFTR KTEST KUNPCK KXNOR KXOR
syn keyword fasmInstr VALIGND VALIGNQ VBLENDMPD VBLENDMPS VBROADCASTF32X2 VBROADCASTF32X4 VBROADCASTF32X8 VBROADCASTF64X2 VBROADCASTF64X4 VBROADCASTI32X2 VBROADCASTI32X4 VBROADCASTI32X8 VBROADCASTI64X2 VBROADCASTI64X4 VCMPEQ_OQPD VCMPEQ_OQPS VCMPEQ_OQSD VCMPEQ_OQSS VCOMPRESSPD VCOMPRESSPS VCVTPD2QQ VCVTPD2UDQ VCVTPD2UQQ VCVTPS2QQ VCVTPS2UDQ VCVTPS2UQQ VCVTQQ2PD VCVTQQ2PS VCVTSD2USI VCVTSS2USI VCVTTPD2QQ VCVTTPD2UDQ VCVTTPD2UQQ VCVTTPS2QQ VCVTTPS2UDQ VCVTTPS2UQQ VCVTTSD2USI VCVTTSS2USI VCVTUDQ2PD VCVTUDQ2PS VCVTUQQ2PD VCVTUQQ2PS VCVTUSI2SD VCVTUSI2SS VDBPSADBW VEXP2PD VEXP2PS VEXPANDPD VEXPANDPS VEXTRACTF32X4 VEXTRACTF32X8 VEXTRACTF64X2 VEXTRACTF64X4 VEXTRACTI32X4 VEXTRACTI32X8 VEXTRACTI64X2 VEXTRACTI64X4 VFIXUPIMMPD VFIXUPIMMPS VFIXUPIMMSD VFIXUPIMMSS VFPCLASSPD VFPCLASSPS VFPCLASSSD VFPCLASSSS VGATHERPF0DPD VGATHERPF0DPS VGATHERPF0QPD VGATHERPF0QPS VGATHERPF1DPD VGATHERPF1DPS VGATHERPF1QPD VGATHERPF1QPS VGETEXPPD VGETEXPPS VGETEXPSD VGETEXPSS VGETMANTPD VGETMANTPS VGETMANTSD VGETMANTSS VINSERTF32X4 VINSERTF32X8 VINSERTF64X2 VINSERTF64X4 VINSERTI32X4 VINSERTI32X8 VINSERTI64X2 VINSERTI64X4 VMOVDQA32 VMOVDQA64 VMOVDQU16 VMOVDQU32 VMOVDQU64 VMOVDQU8 VPABSQ VPANDD VPANDND VPANDNQ VPANDQ VPBLENDMB VPBLENDMD VPBLENDMQ VPBLENDMW VPBROADCASTMB2Q VPBROADCASTMW2D VPCMPEQUB VPCMPEQUD VPCMPEQUQ VPCMPEQUW VPCMPGEB VPCMPGED VPCMPGEQ VPCMPGEUB VPCMPGEUD VPCMPGEUQ VPCMPGEUW VPCMPGEW VPCMPGTUB VPCMPGTUD VPCMPGTUQ VPCMPGTUW VPCMPLEB VPCMPLED VPCMPLEQ VPCMPLEUB VPCMPLEUD VPCMPLEUQ VPCMPLEUW VPCMPLEW VPCMPLTB VPCMPLTD VPCMPLTQ VPCMPLTUB VPCMPLTUD VPCMPLTUQ VPCMPLTUW VPCMPLTW VPCMPNEQB VPCMPNEQD VPCMPNEQQ VPCMPNEQUB VPCMPNEQUD VPCMPNEQUQ VPCMPNEQUW VPCMPNEQW VPCMPNGTB VPCMPNGTD VPCMPNGTQ VPCMPNGTUB VPCMPNGTUD VPCMPNGTUQ VPCMPNGTUW VPCMPNGTW VPCMPNLEB VPCMPNLED VPCMPNLEQ VPCMPNLEUB VPCMPNLEUD VPCMPNLEUQ VPCMPNLEUW VPCMPNLEW VPCMPNLTB VPCMPNLTD VPCMPNLTQ VPCMPNLTUB VPCMPNLTUD VPCMPNLTUQ VPCMPNLTUW VPCMPNLTW VPCMPB VPCMPD VPCMPQ VPCMPUB VPCMPUD VPCMPUQ VPCMPUW VPCMPW VPCOMPRESSD VPCOMPRESSQ VPCONFLICTD VPCONFLICTQ VPERMB VPERMI2B VPERMI2D VPERMI2PD VPERMI2PS VPERMI2Q VPERMI2W VPERMT2B VPERMT2D VPERMT2PD VPERMT2PS VPERMT2Q VPERMT2W VPERMW VPEXPANDD VPEXPANDQ VPLZCNTD VPLZCNTQ VPMAXSQ VPMAXUQ VPMINSQ VPMINUQ VPMOVB2M VPMOVD2M VPMOVDB VPMOVDW VPMOVM2B VPMOVM2D VPMOVM2Q VPMOVM2W VPMOVQ2M VPMOVQB VPMOVQD VPMOVQW VPMOVSDB VPMOVSDW VPMOVSQB VPMOVSQD VPMOVSQW VPMOVSWB VPMOVUSDB VPMOVUSDW VPMOVUSQB VPMOVUSQD VPMOVUSQW VPMOVUSWB VPMOVW2M VPMOVWB VPMULLQ VPMULTISHIFTQB VPORD VPORQ VPROLD VPROLQ VPROLVD VPROLVQ VPRORD VPRORQ VPRORVD VPRORVQ VPSCATTERDD VPSCATTERDQ VPSCATTERQD VPSCATTERQQ VPSLLVW VPSRAQ VPSRAVQ VPSRAVW VPSRLVW VPTERNLOGD VPTERNLOGQ VPTESTMB VPTESTMD VPTESTMQ VPTESTMW VPTESTNMB VPTESTNMD VPTESTNMQ VPTESTNMW VPXORD VPXORQ VRANGEPD VRANGEPS VRANGESD VRANGESS VRCP14PD VRCP14PS VRCP14SD VRCP14SS VRCP28PD VRCP28PS VRCP28SD VRCP28SS VREDUCEPD VREDUCEPS VREDUCESD VREDUCESS VRNDSCALEPD VRNDSCALEPS VRNDSCALESD VRNDSCALESS VRSQRT14PD VRSQRT14PS VRSQRT14SD VRSQRT14SS VRSQRT28PD VRSQRT28PS VRSQRT28SD VRSQRT28SS VSCALEFPD VSCALEFPS VSCALEFSD VSCALEFSS VSCATTERDPD VSCATTERDPS VSCATTERPF0DPD VSCATTERPF0DPS VSCATTERPF0QPD VSCATTERPF0QPS VSCATTERPF1DPD VSCATTERPF1DPS VSCATTERPF1QPD VSCATTERPF1QPS VSCATTERQPD VSCATTERQPS VSHUFF32X4 VSHUFF64X2 VSHUFI32X4 VSHUFI64X2
syn keyword fasmInstr RDPKRU WRPKRU
syn keyword fasmInstr RDPID
syn keyword fasmInstr CLFLUSHOPT CLWB PCOMMIT
syn keyword fasmInstr CLZERO
syn keyword fasmInstr PTWRITE
syn keyword fasmInstr CLDEMOTE MOVDIRI MOVDIR64B PCONFIG TPAUSE UMONITOR UMWAIT WBNOINVD
syn keyword fasmInstr GF2P8AFFINEINVQB VGF2P8AFFINEINVQB GF2P8AFFINEQB VGF2P8AFFINEQB GF2P8MULB VGF2P8MULB
syn keyword fasmInstr VPCOMPRESSB VPCOMPRESSW VPEXPANDB VPEXPANDW VPSHLDW VPSHLDD VPSHLDQ VPSHLDVW VPSHLDVD VPSHLDVQ VPSHRDW VPSHRDD VPSHRDQ VPSHRDVW VPSHRDVD VPSHRDVQ
syn keyword fasmInstr VPDPBUSD VPDPBUSDS VPDPWSSD VPDPWSSDS
syn keyword fasmInstr VPOPCNTB VPOPCNTW VPOPCNTD VPOPCNTQ VPSHUFBITQMB
syn keyword fasmInstr V4FMADDPS V4FNMADDPS V4FMADDSS V4FNMADDSS
syn keyword fasmInstr V4DPWSSDS V4DPWSSD
syn keyword fasmInstr ENCLS ENCLU ENCLV
syn keyword fasmInstr CLRSSBSY ENDBR32 ENDBR64 INCSSPD INCSSPQ RDSSPD RDSSPQ RSTORSSP SAVEPREVSSP SETSSBSY WRUSSD WRUSSQ WRSSD WRSSQ
syn keyword fasmInstr ENQCMD ENQCMDS SERIALIZE XRESLDTRK XSUSLDTRK
syn keyword fasmInstr VCVTNE2PS2BF16 VDPBF16PS
syn keyword fasmInstr VP2INTERSECTD
syn keyword fasmInstr LDTILECFG STTILECFG TDPBF16PS TDPBSSD TDPBSUD TDPBUSD TDPBUUD TILELOADD TILELOADDT1 TILERELEASE TILESTORED TILEZERO
syn keyword fasmInstr VADDPH VADDSH VCMPPH VCMPSH VCOMISH VCVTDQ2PH VCVTPD2PH VCVTPH2DQ VCVTPH2PD VCVTPH2PSX VCVTPH2QQ VCVTPH2UDQ VCVTPH2UQQ VCVTPH2UW VCVTPH2W VCVTQQ2PH VCVTSD2SH VCVTSH2SD VCVTSH2SI VCVTSH2SS VCVTSH2USI VCVTSI2SH VCVTSS2SH VCVTTPH2DQ VCVTTPH2QQ VCVTTPH2UDQ VCVTTPH2UQQ VCVTTPH2UW VCVTTPH2W VCVTTSH2SI VCVTTSH2USI VCVTUDQ2PH VCVTUQQ2PH VCVTUSI2SH VCVTUW2PH VCVTW2PH VDIVPH VDIVSH VFCMADDCPH VFMADDCPH VFCMADDCSH VFMADDCSH VFCMULCPCH VFMULCPCH VFCMULCSH VFMULCSH VFMADDSUB132PH VFMADDSUB213PH VFMADDSUB231PH VFMSUBADD132PH VFMSUBADD213PH VFMSUBADD231PH VPMADD132PH VPMADD213PH VPMADD231PH VFMADD132PH VFMADD213PH VFMADD231PH VPMADD132SH VPMADD213SH VPMADD231SH VPNMADD132SH VPNMADD213SH VPNMADD231SH VPMSUB132PH VPMSUB213PH VPMSUB231PH VFMSUB132PH VFMSUB213PH VFMSUB231PH VPMSUB132SH VPMSUB213SH VPMSUB231SH VPNMSUB132SH VPNMSUB213SH VPNMSUB231SH VFPCLASSPH VFPCLASSSH VGETEXPPH VGETEXPSH VGETMANTPH VGETMANTSH VGETMAXPH VGETMAXSH VGETMINPH VGETMINSH VMOVSH VMOVW VMULPH VMULSH VRCPPH VRCPSH VREDUCEPH VREDUCESH VENDSCALEPH VENDSCALESH VRSQRTPH VRSQRTSH VSCALEFPH VSCALEFSH VSQRTPH VSQRTSH VSUBPH VSUBSH VUCOMISH
syn keyword fasmInstr AADD AAND AXOR
syn keyword fasmInstr CLUI SENDUIPI STUI TESTUI UIRET
syn keyword fasmInstr CMPBEXADD CMPBEXADD CMPBEXADD CMPBXADD CMPBXADD CMPBXADD CMPLEXADD CMPLEXADD CMPLEXADD CMPLXADD CMPLXADD CMPLXADD CMPNBEXADD CMPNBEXADD CMPNBEXADD CMPNBXADD CMPNBXADD CMPNBXADD CMPNLEXADD CMPNLEXADD CMPNLEXADD CMPNLXADD CMPNLXADD CMPNLXADD CMPNOXADD CMPNOXADD CMPNPXADD CMPNPXADD CMPNSXADD CMPNSXADD CMPNZXADD CMPNZXADD CMPOXADD CMPOXADD CMPPXADD CMPPXADD CMPSXADD CMPSXADD CMPZXADD CMPZXADD
syn keyword fasmInstr ERETS ERETU LKGS
syn keyword fasmInstr WRMSRNS RDMSRLIST WRMSRLIST
syn keyword fasmInstr HRESET
syn keyword fasmInstr HINT_NOP0 HINT_NOP1 HINT_NOP2 HINT_NOP3 HINT_NOP4 HINT_NOP5 HINT_NOP6 HINT_NOP7 HINT_NOP8 HINT_NOP9 HINT_NOP10 HINT_NOP11 HINT_NOP12 HINT_NOP13 HINT_NOP14 HINT_NOP15 HINT_NOP16 HINT_NOP17 HINT_NOP18 HINT_NOP19 HINT_NOP20 HINT_NOP21 HINT_NOP22 HINT_NOP23 HINT_NOP24 HINT_NOP25 HINT_NOP26 HINT_NOP27 HINT_NOP28 HINT_NOP29 HINT_NOP30 HINT_NOP31 HINT_NOP32 HINT_NOP33 HINT_NOP34 HINT_NOP35 HINT_NOP36 HINT_NOP37 HINT_NOP38 HINT_NOP39 HINT_NOP40 HINT_NOP41 HINT_NOP42 HINT_NOP43 HINT_NOP44 HINT_NOP45 HINT_NOP46 HINT_NOP47 HINT_NOP48 HINT_NOP49 HINT_NOP50 HINT_NOP51 HINT_NOP52 HINT_NOP53 HINT_NOP54 HINT_NOP55 HINT_NOP56 HINT_NOP57 HINT_NOP58 HINT_NOP59 HINT_NOP60 HINT_NOP61 HINT_NOP62 HINT_NOP63

syn keyword fasmMacros         addr cinvoke endf endl endp ends feature frame invoke local locals proc stdcall struct uses
syn keyword fasmMacroDirective common forward local reverse
syn keyword fasmPreprocess     define equ fix forward include irp irps
syn keyword fasmPreprocess     local macro match purge rept restore restruc struc
syn keyword fasmDirective      assert binary code coff console data display discardable dll dynamic elf elf64 else end
syn keyword fasmDirective      entry executable efiboot err far fixups format gui if import interpreter label library linkinfo
syn keyword fasmDirective      ms ms64 mz native near needed notpageable pe pe64 resource readable repeat section
syn keyword fasmDirective      shareable static segment use16 use32 use64 virtual wdm writable writeable
syn keyword fasmOperator       align as at defined eq eqtype from mod on ptr rva relativeto used

syn match   fasmConstants       "\<[A-Z_]\+[A-Z_0-9]\*b\>"
syn match   fasmNumericOperator "[+-/*]"
syn match   fasmLogicalOperator "[=|&~<>]\|<=\|>=\|<>"
syn match   fasmBinaryNumber    "\<[01]\+b\>"
syn match   fasmHexNumber       "\<\d\x*h\>"
syn match   fasmHexNumber       "\<\(0x\|$\)\x*\>"
syn match   fasmFPUNumber       "\<\d\+\(\.\d*\)\=\(e[-+]\=\d*\)\=\>"
syn match   fasmOctalNumber     "\<\(0\o\+o\=\|\o\+o\)\>"
syn match   fasmDecimalNumber   "\<\(0\|[1-9]\d*\)\>"
syn region  fasmComment         start=";" end="$"
syn region  fasmString          start="\"" end="\"\|$"
syn region  fasmString          start="'" end="'\|$"
syn match   fasmSymbol          "[<>()|\[\]:]"
syn match   fasmSpecial         "[#?%$,]"
syn match   fasmLabel           "^\s*[^; \t]\+:"

hi def link fasmAddressSizes    type
hi def link fasmNumericOperator fasmOperator
hi def link fasmLogicalOperator fasmOperator

hi def link fasmBinaryNumber    fasmNumber
hi def link fasmHexNumber       fasmNumber
hi def link fasmFPUNumber       fasmNumber
hi def link fasmOctalNumber     fasmNumber
hi def link fasmDecimalNumber   fasmNumber

hi def link fasmSymbols         fasmRegister
hi def link fasmPreprocess      fasmDirective
hi def link fasmMacroDirective  fasmDirective

hi def link fasmConstants      Identifier
hi def link fasmOperator       Operator
hi def link fasmComment        Comment
hi def link fasmDirective      PreProc
hi def link fasmRegister       Type
hi def link fasmNumber         Constant
hi def link fasmSymbol         Structure
hi def link fasmString         String
hi def link fasmSpecial        Special
hi def link fasmInstr          Keyword
hi def link fasmLabel          Label
hi def link fasmPrefix         Statement
hi def link fasmMacros         Identifier
hi def link fasmDataDirectives StorageClass

let b:current_syntax = "fasm"

let &cpo = s:cpo_save
unlet s:cpo_save
